### ISSUE TITLE
Bugs: hide-and-seek Exercise

### ISSUE THREAD

**Issue by Kaweesi-Matia** [MudasirSherwani/Portfolio#13]
### The branch "[Form-Validation-With-Javascript]" is discussed in this exercise.
**Problem I faced:**
when I tried to submit the contact form data it generated an error even though I put the valid email address in lowercase.
**Debugging**
During the debugging process, I found the bug with the help of a developer tool in the google chrome browser.
I have added two checkpoints with the console.log() function into the variable received from the HTML contact form email address and another checkpoint console.loge() I add to the value we require from contact form validation.
after that I check the value of the console.log() function from the browser console tab, here both values were the same and I found that the code is receiving the valid values that the function required but there was an error in the conditional comparison. 
**The solution**
 I have fixed the bug after applying of correct condition to the if statement.

**Comment by MudasirSherwani** [comment]
Hi @Kaweesi-Matia :wave: 
Thanks to help me in debugging and provide the best solution.
