### ISSUE TITLE
Peer to peer Review

### ISSUE THREAD

**Issue by rugwizangoga** [MudasirSherwani/Portfolio#7]
In this issue, we will give a review, make a suggestion  and appreciate what was done right

**Comment by rugwizangoga** [comment]
![nice](https://user-images.githubusercontent.com/57993089/186997194-fe3ab17b-0a27-459e-bfd3-c533099dbcaf.gif)

- Clean codes
- no linter errors
- professional GitHub workflow
- professional documentation
- responsive and mobile-first designing

**Comment by MudasirSherwani** [comment]
Hi @rugwizangoga :wave: 
Thanks so much for such a lovely review.
